export const movieSupercode = [
   {
      name: 'Julia',
      adult: false,
      backdrop_path: null,
      genre_ids: [10751],
      id: 55599555,
      original_language: 'en',
      original_title: 'Julia - Supercoder of Supercode',
      overview: 'Julia, who teaches all the participants how to program so that they all become super programmers.',
      popularity: 3.958,
      poster_path: 'julia',
      release_date: '2023-02-01',
      title: 'Julia - Supercoderin von Supercode',
      video: false,
      vote_average: 100,
      vote_count: 1,
      runtime: 500,
   },
   {
      name: 'Freddy',
      adult: false,
      backdrop_path: null,
      genre_ids: [10751],
      id: 55588555,
      original_language: 'en',
      original_title: 'Freddy - Supercoder of Supercode',
      overview: 'Freddy is very happy with his family as they now have one more family member and he loves coding at supercode.',
      popularity: 3.958,
      poster_path: 'freddy',
      release_date: '2023-02-01',
      title: 'Freddy - Supercoder of Supercode',
      video: false,
      vote_average: 100,
      vote_count: 1,
      runtime: 500,
   },
   {
      name: 'Steffen',
      adult: false,
      backdrop_path: null,
      genre_ids: [10751],
      id: 55577555,
      original_language: 'en',
      original_title: 'Steffen - Supercoder of Supercode',
      overview: 'Steffen is happy with his Filament for 3D Printer and his work by Supercode',
      popularity: 3.958,
      poster_path: 'steffen',
      release_date: '2023-02-01',
      title: 'Steffen - Supercoder of Supercode',
      video: false,
      vote_average: 100,
      vote_count: 1,
      runtime: 500,
   },
];
