export const myMovieArray = [
   {
      name: 'Freddy',
      adult: false,
      backdrop_path: null,
      genre_ids: [10751],
      id: 946584,
      original_language: 'en',
      original_title: 'Freddy der Supercoder von Supercode',
      overview: "Marvel and DC's",
      popularity: 3.958,
      poster_path: 'freddy',
      release_date: '2023-03-04',
      title: 'Freddy der Supercoder von Supercode',
      video: false,
      vote_average: 100,
      vote_count: 1,
   },
   {
      name: 'Julia',
      adult: false,
      backdrop_path: null,
      genre_ids: [10751],
      id: 946584,
      original_language: 'en',
      original_title: 'Freddy der Supercoder von Supercode',
      overview: "Marvel and DC's",
      popularity: 3.958,
      poster_path: 'freddy',
      release_date: '2023-03-04',
      title: 'Freddy der Supercoder von Supercode',
      video: false,
      vote_average: 100,
      vote_count: 1,
   },
   {
      name: 'Steffen',
      adult: false,
      backdrop_path: null,
      genre_ids: [10751],
      id: 56985326984365,
      original_language: 'en',
      original_title: 'Freddy der Supercoder von Supercode',
      overview: "Marvel and DC's",
      popularity: 3.958,
      poster_path: 'freddy',
      release_date: '2023-03-04',
      title: 'Freddy der Supercoder von Supercode',
      video: false,
      vote_average: 100,
      vote_count: 1,
   },
];
